### PR TITLE
Removing dependency on config_path function.

### LINKED ISSUE #67: Compatibility with Lumen
The `AwsServiceProvider` currently doesn't work in a Lumen project, because the `config_path` helper function isn't available.

Would it be reasonable to change line 9 (`$this->publishes...`) to first check to see if `config_helper` has been defined?

From what I can tell `$this->publishes...` doesn't need to be run in a Lumen app anyway, and I can still configure Aws using my .env file.

I'd be happy to submit a PR, just wanted to see if this was the right approach.

### PR DESCRIPTION
**Pull request by jeremeamia**
Possibly fixes #67

### CODE REVIEW

**Comment by jeremeamia** [comment]
@GrahamCampbell That look right?

File: src/AwsServiceProvider.php [hunk 1]
```diff
@@ -26,7 +26,9 @@ public function boot()
 
         $this->mergeConfigFrom($config, 'aws');
 
-        $this->publishes([$config => config_path('aws.php')], 'config');
+        $this->publishes([
+            $config => $this->app->make('path.config') . DIRECTORY_SEPARATOR . 'aws.php'
```
Comment (GrahamCampbell) [inline src/AwsServiceProvider.php]: DIRECTORY_SEPARATOR not really needed

**Comment by GrahamCampbell** [comment]
In principle, yeh, it looks fine. :)
